### PR TITLE
Update settings.json: add pre/post_uninstall fields to sortJSON lists

### LINKED ISSUE #1183: [Bug]: pre_uninstall and post_uninstall fields missing from sortJSON lists in settings.json
Running the Sort JSON command against manifest containing either the `pre_uninstall` or `post_uninstall` fields may result in unintended modifications to a properly sorted manifest. 

For example, running Sort JSON against bloxstrap.json moves the `pre_uninstall` block below `autoupdate` which does not adhere to the desired field order as described in [CONTRIBUTING.md](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Adding these fields to the list of fields in settings.json should correct this issue.

### PR DESCRIPTION
**Pull request by mundifex**
Add missing `pre_uninstall` and `post_uninstall` entries to sortJSON field list in settings.json.

Closes #1183

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Thanks!

**Comment by Calinou** [comment]
Could you commit sorted files in this PR to fix CI?

**Comment by mundifex** [comment]
> Could you commit sorted files in this PR to fix CI?

Will do.

**Comment by mundifex** [comment]
I am unable to reproduce the CI failures locally. 

Things I've tried:
- run `.\bin\test.ps1` within a PowerShell terminal in VSCode using my local bucket repo as a working directory
- recreate `d:\a\scoop-games\...` folder structure following the steps taken by Tests / PowerShell 
- execute the following with `d:\a\scoop-games\scoop-games\` as a working directory:
```
$env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
.\scoop_core\test\bin\init.ps1
.\my_bucket\bin\test.ps1
```

In all cases, every test passes OK. Nothing ever attempts to validate settings.json like CI seems to be doing.

I made a quick PR (#1186) that introduced a bogus config value and it also [resulted in CI failure](https://github.com/Calinou/scoop-games/actions/runs/9814939893/job/27103305308?pr=1186), so it seems that any modification to settings.json will result in test failure.

Am I doing something wrong? Is there something more I can try?

**Comment by Calinou** [comment]
Let's merge this either way and see if CI failures remain in the future.

**Pull request merged**
