### PR TITLE
ppsspp(-dev): Fix manifests, Update `test.ps1` to Pester 5

### PR DESCRIPTION
**Pull request by sitiom**
- Fix outdated `ppsspp(-dev)` manifests
- Update to Pester 5, See https://github.com/ScoopInstaller/Scoop/releases/tag/v0.3.1:
>### BREAKING CHANGES
>
>- **pester:** Update to Pester 5 (https://github.com/ScoopInstaller/Scoop/pull/5222)
>
>#### IMPORTANT FOR BUCKET MAINTAINERS
>
>- Pester 5 is used in this release. To make sure your bucket's CI works properly, please update `bin\test.ps1` from Pester 4 to Pester 5.
>- You can use `test.ps1` attached in the release files.

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Thanks!

**Comment by Calinou** [comment]
There are CI failures due to ppsspp-dev and ppsspp. Would you mind fixing those manifests in this PR so it can be merged with successful CI?

**Comment by sitiom** [comment]
@Calinou all good

**Comment by sitiom** [comment]
@Calinou bump

**Comment by sitiom** [comment]
Errors due to unrelated files:
image

**Comment by Calinou** [comment]
Needs a rebase again (sorry, I wasn't at my PC today).

**Comment by sitiom** [comment]
@Calinou done

**Review by Calinou — APPROVED** [review]
Thanks!

**Review by Calinou — COMMENTED** [review]
Sorry, I accidentally undid some of your changes during conflict resolution. (It's not obvious what "current change" and "incoming change" refer to in GitHub's online conflict resolution dialog…).

**Comment by sitiom** [comment]
All fixed 🙂

**Pull request merged**
