### PR TITLE
prismlauncher: Add version 5.0

### LINKED ISSUE #721: Request: Add Prism Launcher
As a result of #720, much of the team that once made PolyMC has made [PrismLauncher](https://github.com/PrismLauncher/PrismLauncher). As of a few minutes ago, they have made the first versioned release, [5.0](https://github.com/PrismLauncher/PrismLauncher/releases/5.0) (inherited from PolyMC). [Here's a direct portable download link](https://github.com/PrismLauncher/PrismLauncher/releases/download/5.0/PrismLauncher-Windows-Portable-5.0.zip).

This issue basically serves as a (potentially unneeded) successor to #720, but it's probably big enough that it can get its own issue. I mean, 1.2k stars and 77 forks in 2 days is quite impressive 😅

### PR DESCRIPTION
**Pull request by alyti**
Closes #721 #720

- [X] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by DioEgizio** [comment]
lgtm, but add prismlauncher-qt5 too

**Comment by Calinou** [comment]
There's also https://github.com/Calinou/scoop-games/pull/723/files which adds the Qt5 version.

**Comment by alyti** [comment]
just added qt5 variant @Calinou

**Comment by Calinou** [comment]
Superseded by https://github.com/Calinou/scoop-games/pull/723 (which had more complete `description`s). Thanks for the contribution nonetheless!

**Pull request closed without merging**
