### PR TITLE
chunker: Add version 1.0.0

### PR DESCRIPTION
**Pull request by RuiNtD**
Relates to #1203

- [X] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Thanks!

**Review by Calinou — CHANGES_REQUESTED** [review]
Indentation needs to be replaced with spaces before this can be merged.

**Comment by RuiNtD** [comment]
@Calinou I did request re-review BTW.

**Review by Calinou — APPROVED** [review]

**Pull request merged**
