### PR TITLE
mgba-dev: fix hash + clean versioning

### PR DESCRIPTION
**Pull request by BlackPowerade**
`Updating 'mgba-dev' (0.7.3-5983-b7bbe0a -> 0.7.3-5984-2583c5c)
Downloading new version
mGBA-build-latest-win64.7z (10.6 MB) [================================================================] 100%
Checking hash of mGBA-build-latest-win64.7z ... ERROR Hash check failed!
App:         games/mgba-dev
URL:         https://s3.amazonaws.com/mgba/mGBA-build-latest-win64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    11fc940bdc8d3e9e2c608af9a28ffc1a93db23d69241da2fe28d4d8b6fe13c40
Actual:      b5831a1a67d57f1ebdc78776dd327135ffcb20a6d3438ba0ff56358afaae9ae2`
Also pushes to latest version `0.7.3-5985`

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks!

**Comment by Calinou** [comment]
There are merge conflicts due to today's automatic update, could you fix them? I'll merge this once this is done :slightly_smiling_face:

**Comment by BlackPowerade** [comment]
@Calinou Please merge ASAP before autoupdate causes merge conflicts again.

**Comment by Calinou** [comment]
Thanks! 

Sorry for the delay.

**Pull request merged**
