### PR TITLE
Sudachi: add version v7715077

### PR DESCRIPTION
**Pull request by SandeMC**
Adds sudachi, a continuation of the yuzu emulator project. Compared to suyu, this project actually attempts to advance emulation code and has already made (minor) progress on making newer games work.

Relates to https://github.com/Calinou/scoop-games/issues/1100 and https://github.com/Calinou/scoop-games/issues/1101

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SandeMC** [comment]
??? can somebody point me to what's wrong

**Comment by SandeMC** [comment]
It's based on build numbers, so not sure if this will actually work as it should

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
