### PR TITLE
wesnoth: add checkver and autoupdate

### PR DESCRIPTION
**Pull request by issaclin32**
Please let me know if there are any problems. Thanks.

### CODE REVIEW

**Comment by r15ch13** [comment]
Hash extraction be simplified to `$url.sha256`.

**Comment by issaclin32** [comment]
> Hash extraction could be simplified to `$url.sha256`.

Thanks for the suggestion.

They provide SHA-256 checksum file for Linux and Mac versions, but not for Windows version (not sure why). Therefore `$url.sha256` does not work for this one.
(see: https://sourceforge.net/projects/wesnoth/files/wesnoth-1.14/wesnoth-1.14.7/)

**Comment by r15ch13** [comment]
On the official page they provide the checksum file for windows:
`https://files.wesnoth.org/releases/wesnoth-1.14.7-win32.exe.sha256`

So `https://files.wesnoth.org/releases/wesnoth-$version-win32.exe.sha256` is less prone to errors that a regex. :smile:

**Comment by r15ch13** [comment]
Updated manifest:
```json
{
    "homepage": "https://www.wesnoth.org/",
    "description": "Turn-based singleplayer and multiplayer strategy game with a high fantasy theme",
    "version": "1.14.7",
    "license": "GPL-2.0-or-later",
    "url": "https://downloads.sourceforge.net/project/wesnoth/wesnoth-1.14/wesnoth-1.14.7/wesnoth-1.14.7-win32.exe#/dl.7z",
    "hash": "31b2acfa65cb383012c04c8adbe903b6c3a6ef6a7a32d02a5c49e2e8fcd8ca26",
    "shortcuts": [
        [
            "wesnoth.exe",
            "The Battle for Wesnoth"
        ]
    ],
    "checkver": {
        "url": "https://wiki.wesnoth.org/Download",
        "regex": "wesnoth-([\\d.]+)-win32.exe"
    },
    "autoupdate": {
        "url": "https://downloads.sourceforge.net/project/wesnoth/wesnoth-$majorVersion.$minorVersion/wesnoth-$version/wesnoth-$version-win32.exe#/dl.7z",
        "hash": {
            "url": "https://files.wesnoth.org/releases/wesnoth-$version-win32.exe.sha256"
        }
    }
}
```

**Comment by issaclin32** [comment]
> On the official page they provide the checksum file for windows:
> `https://files.wesnoth.org/releases/wesnoth-1.14.7-win32.exe.sha256`

Thanks for the information.

**Pull request merged**
