### PR TITLE
tooniversal: Add version 1.1.0

### PR DESCRIPTION
**Pull request by NoraTheGamer**

### CODE REVIEW

**Comment by NoraTT** [comment]
Wget is failing since its version flag does not have a comma. it is not this package.

**Comment by NoraTheGamer** [comment]
Mind reviewing this PR?

**Comment by Calinou** [comment]
By the way, what's the difference between `tooniversal`, `corporateclash` and `toontownrewritten`? Which one of them is the most popular?

**Review by Calinou — APPROVED** [review]
Tested locally, it works. Thanks!

**Pull request merged**
