### PR TITLE
special-k: Add version 23.9.10.1

### PR DESCRIPTION
**Pull request by FlawlessCasual17**
Adds Special K, “the Swiss army knife of PC gaming” to this scoop bucket.

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Calinou** [comment]
I wonder if this would be better part of the Extras bucket instead, so that it's in the same location as tools like RTSS.

**Comment by FlawlessCasual17** [comment]
Do you think it should go in the extras bucket?

**Comment by FlawlessCasual17** [comment]
I don't mind putting this in another bucket

**Comment by FlawlessCasual17** [comment]
I'm not sure to be honest

**Comment by Calinou** [comment]
> Do you think it should go in the extras bucket?

Yes, I try to keep this bucket strictly about games and game-related tools, but Special-K is general enough that it can be useful to install as a development tool (for troubleshooting system performance or profiling).

**Comment by FlawlessCasual17** [comment]
Maybe not in the **extras** bucket, it should go in the **non-portable** bucket since _Special K_ is pretty difficult to manually install, so I would rather let the installer do all the hard work.

**Pull request closed without merging**
