### PR TITLE
zandronum: Update to 3.1

### LINKED ISSUE #748: Update Zandronum
The latest stable version is now 3.1. Then, please make these changes for a better integration with Scoop:

```json
"pre_install": [
        "New-Item -ItemType Directory -Force -Path $persist_dir\\..\\_doom | Out-Null",
        "(@(\"[IWADSearch.Directories]`nPath=.`nPath=$DOOMWADDIR`nPath=$HOME`n`n[FileSearch.Directories]`nPath=$PROGDIR`nPath=$DOOMWADDIR/zandronum`n`n\") +  \"[GlobalSettings]`nscreenshot_dir=screenshots`nscreenshot_type=png`nsave_dir=SAVE`ncrashlog_dir=crashes`ncrashlogs=1`ndatabasefile=data/database.sqlite`nsv_adminlistfile=data/adminlist.txt`nsv_banexemptionfile=data/whitelist.txt`nsv_banfile=data/banlist.txt`nstatfile=data/zdoomstats.txt`ngus_patchdir=data/gus`nmidi_config=data/timidity.cfg`n\") -join '' | New-Item -ItemType File -Path \"$dir/zandronum_portable.ini\" -ErrorAction Ignore | Out-Null"
    ],
    "post_install": "New-Item -Path $dir\\zandronum-$($env:USERNAME).ini -Value $persist_dir\\zandronum_portable.ini -ItemType SymbolicLink -ErrorAction Ignore | Out-Null",
    "persist": [
        "zandronum_portable.ini",
        "addons",
        "announcer",
        "autoload",
        "cfg",
        "data",
        "crashes",
        "demos",
        "logs",
        "SAVE",
        "screenshots",
        "skins"
    ],
```

### PR DESCRIPTION
**Pull request by Zliced13**
Added `checkver`, `autoupdate`, `persist`, fix `pre_install`, and add `pre_uninstall`

Closes #748

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Thanks!

**Comment by ZzZombo** [comment]
Am I missing something? It appears you did follow my suggestions in the linked issue thread, but omitted the part that actually makes the game to use the persisted folders in the configuration file.

**Comment by Zliced13** [comment]
@ZzZombo you don't have to worry, the `pre_(un)install` scripts will copy the user's config to the persist folder and vice versa.

**Comment by ZzZombo** [comment]
But the default config doesn't come with those values. They were my modifications to better accommodate Scoop.

**Comment by Zliced13** [comment]
Ok I will open another PR to add your fixes to it, I hope it works better than what I did.

**Pull request merged**
