### PR TITLE
Update Mindustry & Mindustry Server to v109

### PR DESCRIPTION
**Pull request by dudeamax99**

### CODE REVIEW

**Comment by Calinou** [comment]
Shouldn't the `autoupdate` be doing its job in less than 24 hours from now?

**Review by Calinou — APPROVED** [review]
Thanks!

PS: In the future, no need to open pull requests as the bot will update all packages with an `autoupdate` property every 24 hours.

**Comment by dudeamax99** [comment]
Did it break? When I made #155, [v108](https://github.com/Anuken/Mindustry/releases/tag/v108) had been out for 2 days. I made this one cause I didn't think there was any automation.

**Comment by Calinou** [comment]
cc @r15ch13 who maintains the bot.

**Pull request merged**
