### PR TITLE
Create scummvm.json

### PR DESCRIPTION
**Pull request by helohe**
Did not figure out how to test it. But added this.

### CODE REVIEW

**Comment by Calinou** [comment]
It works, but I'm being prompted for an update immediately after running it for the first time. Unfortunately, accepting it will cause ScummVM from downloading an installer which will install a separate version

Is there a way to disable automatic updates by default?

**Comment by r15ch13** [comment]
- `scummvm.ini` is located in `%appdata%\ScummVM`
  - can not be loaded from the current directory
  - https://github.com/scummvm/scummvm/blob/v2.1.1/README.md#80-configuration-file
- Update is WinSparkle
  - https://www.scummvm.org/appcasts/macosx/release.xml
  - `macosx` in the URL is correct

**Comment by 7wells** [comment]
Hello, what does it take to get this done and closed? Or has this been abandoned?

**Comment by Calinou** [comment]
> Hello, what does it take to get this done and closed? Or has this been abandoned?

Feedback from https://github.com/Calinou/scoop-games/pull/93#issuecomment-593325536 needs to be applied, but I don't know how to do it exactly.

**Comment by 7wells** [comment]
@r15ch13
It's a year ago, sorry to bring this up again. Can you maybe help? Thank you.

**Comment by hlischt** [comment]
Pardon my poor Powershell skills, but wouldn't that issue be fixed with the following post-install script?

```json
"post_install": "if (!(Test-Path \"$env:APPDATA\\ScummVM\\scummvm.ini\")) { New-Item -ItemType directory -Path \"$env:APPDATA\" -Name ScummVM ; printf \"[scummvm]\\nupdates_check=0\\nversioninfo=%s\" \"$version\" | Out-File -Encoding ascii \"$env:APPDATA\\ScummVM\\scummvm.ini\" }"
```

**Comment by BlackPowerade** [comment]
It looks like this is doable. Scummvm has a launch flag to define a custom configuration file. `--config`     
This is what I came up with:
```
"pre_install": [
        "if (!(Test-Path \"$persist_dir\")) {",
        "   New-Item -ItemType Directory -Path \"$persist_dir\\saves\" | Out-Null",
        "   New-Item -ItemType Directory -Path \"$persist_dir\\themes\" | Out-Null",
        "   New-Item -ItemType Directory -Path \"$persist_dir\\extras\" | Out-Null",
        "   '[scummvm]', 'updates_check=0', \"savepath=$persist_dir\\saves\", \"themepath=$persist_dir\\themes\", \"extrapath=$persist_dir\\extras\" | Set-Content \"$persist_dir\\scummvm.ini\"",
        "}"
    ],
```
Shortcut config:    
```
"shortcuts": [
        [
            "scummvm.exe",
            "ScummVM",
            "--config=\"$persist_dir\\scummvm.ini\""
        ]
    ],
```
And persist:     
```
"persist": [
        "scummvm.ini",
        "saves",
        "themes",
        "extras"
    ],
```

I would also recommend shortening the description, the current one is too long.

**Comment by Calinou** [comment]
Superseded by https://github.com/Calinou/scoop-games/pull/516. Thanks for the contribution nonetheless!

**Pull request closed without merging**
