### PR TITLE
Fix manifest sorting

### PR DESCRIPTION
**Pull request by beyondmeat**
This fixes the sort due to architecture having an undocumented sort order

### CODE REVIEW

**Comment by beyondmeat** [comment]
@Calinou would appreciate a quick merge to avoid conflicts, should be last sort pr needed.

**Comment by Calinou** [comment]
Sorry, I was away when you wrote that comment. Could you rebase this PR?

**Comment by beyondmeat** [comment]
@Calinou done

**Comment by beyondmeat** [comment]
@Calinou hope you're online to merge this

**Comment by beyondmeat** [comment]
the build fails due to a dev emu having query params in the url and that's makes schema invalid, but it works and there's no alternative

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
