### PR TITLE
ci: Automatically try to update packages

### PR DESCRIPTION
**Pull request by kiennq**

### CODE REVIEW

**Comment by Calinou** [comment]
@r15ch13 still has their autoupdater running on this repository, should he stop it before I merge this pR?

**Comment by beyondmeat** [comment]
@Calinou if this works, this would be better and update more often

**Comment by r15ch13** [comment]
Should I deactivate it on my end?

**Comment by Calinou** [comment]
> Should I deactivate it on my end?

Yes, I would recommend disabling your updater if this new updater turns out to work out nicely.

**Pull request merged**
