### PR TITLE
suyu: add version 0.0.2-master

### PR DESCRIPTION
**Pull request by grasssand**
- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grasssand** [comment]
Code moved to [homepage](https://git.suyu.dev/suyu/suyu)

**Comment by SandeMC** [comment]
Suyu doesn't have anything related to emulation achieved yet, I wouldn't give them any props or recognition just yet.

**Comment by SandeMC** [comment]
And, as I've said, this project was a fluke. The dev team fell apart and likely won't work on it further, though the kiddo is still trying to look for new developers.

**Pull request closed without merging**
