### PR TITLE
quake-injector: Add version 0.16.20

### LINKED ISSUE #478: Add Quake Injector
Tool to download, install and play Quake 1 singleplayer maps from Quaddicted archive.
Install a development version that does not require the JDK.

https://www.quaddicted.com/tools/quake_injector
https://github.com/hrehfeld/QuakeInjector/releases

### PR DESCRIPTION
**Pull request by Zliced13**
Closes #478

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Calinou** [comment]
Out of curiosity, why was this PR closed?

**Comment by Zliced13** [comment]
The PR closed when I force-pushed the master-branch. Discarding all previous commits, and syncing itself to the latest commits on the head branch.

**Pull request closed without merging**
