### PR TITLE
heroic-games-launcher: Update to 2.9.0

### PR DESCRIPTION
**Pull request by Zliced13**
@Calinou please only merge this PR when the following **Heroic Games Launcher** related issues are resolved.

Updates **`heroic-games-launcher`** to `2.9.0`.

Don't merge this PR until the following issues related to `2.9.0` below are resolved.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2902
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905

- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
Relates to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2902
Relates to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905

**Comment by Zliced13** [comment]
@Calinou do you mind manully rolling heroic games launcher back to 2.8.0, and disable autoupdate until the issues listed above are fixed.

**Comment by Zliced13** [comment]
I'm going to close this PR until the latter issues are resolved.

**Comment by Calinou** [comment]
> I'm going to close this PR until the latter issues are resolved.

It looks like 2.9.1 was just released. It apparently resolved some of the issues: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2902#issuecomment-1652185413

**Comment by Zliced13** [comment]
They also removed arm64 support for Windows, do you mind manually removing it from the `heroic-games-launcher` manifest?

**Comment by Calinou** [comment]
> They also removed arm64 support for Windows, do you mind manually removing it from the `heroic-games-launcher` manifest?

Done: https://github.com/Calinou/scoop-games/commit/8f627911d03c94f594419867cd7bdc3364955ddc

**Comment by Zliced13** [comment]
> > They also removed arm64 support for Windows, do you mind manually removing it from the `heroic-games-launcher` manifest?
> 
> Done: [8f62791](https://github.com/Calinou/scoop-games/commit/8f627911d03c94f594419867cd7bdc3364955ddc)

Thank you very much.

**Pull request closed without merging**
