### PR TITLE
itch: Fix `checkver` to be more accurate

### PR DESCRIPTION
**Pull request by Zliced13**
- [x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Thanks!

**Comment by Zliced13** [comment]
@Calinou its not ready

**Comment by Zliced13** [comment]
@Calinou I'll let you know you know when the PR is ready

**Comment by Zliced13** [comment]
@Calinou it's good now, you can commence the PR merge.

**Pull request merged**
