### PR TITLE
Add gog-galaxy-plugin-downloader

### PR DESCRIPTION
**Pull request by JanPokorny**

### CODE REVIEW

**Comment by Calinou** [comment]
Like #62, I think this would be better suited to [scoop-extras](https://github.com/lukesampson/scoop-extras) as it already contains Steam-related tools.

The idea is to keep this bucket "topical", as it's about *games* and their related tools. Sorry if this is unclear, I should probably write a CONTRIBUTING.md file someday.

**Comment by JanPokorny** [comment]
@Calinou So the idea is that this bucket is primarily for games, and secondarily for tools related to a specific game, like map editors? Maybe include a line like "Game tools should relate to a specific game. General gaming tools and utilities should go to scoop/extras." in the README.

**Comment by Calinou** [comment]
@JanPokorny Exactly :slightly_smiling_face:

**Comment by JanPokorny** [comment]
Moved to https://github.com/lukesampson/scoop-extras/pull/2975.

**Pull request closed without merging**
