### PR TITLE
Update openttd.json

### PR DESCRIPTION
**Pull request by ThatLinuxNerd**
My first time doing this out side of projects of my own, sorry if I might've screwed something up.

### CODE REVIEW

**Comment by ThatLinuxNerd** [comment]
I fucked up the hashes, which means until it gets fixed it can't be installed.

**Comment by Calinou** [comment]
> I fucked up the hashes, which means until it gets fixed it can't be installed if it were to hypothetically be approved in this state.

The new hashes are:

```
928fcf34efd0719a3560cbab6821d71ce686b6315e8825360fba87a7a94d7846  opengfx-7.1-all.zip
8335e12ccb40f803c35c273dc3916c5b0c4f80200ba9091d3de110d11ea7aecc  opengles3-quick-reference-card.pdf
5a4277a2e62d87f2952ea5020dc20fb2f6ffafdccf9913fbf35ad45ee30ec762  openmsx-0.4.2-all.zip
e0a218b7dd9438e701503b0f84c25a97c1c11b7c2f025323fb19d6db16ef3759  opensfx-1.0.3-all.zip
d071b3d8ca71d4df217f3924b371d7e1743d15111a8e4f056470d584eb84d5a1  openttd-12.1-windows-win32.zip
fe909797a3aa9ef1f7080b28685f7a668b8b47fed4db427109e65c3de9468304  openttd-12.1-windows-win64.zip
```

Could you update this pull request to replace the existing hashes? Thanks in advance :slightly_smiling_face:

**Comment by ThatLinuxNerd** [comment]
Will do, thanks.

**Comment by ThatLinuxNerd** [comment]
It's more complicated than that as in recent updates of the game the main contents are no longer on the root of the zip file. I've been trying to find a solution to that issue for a bit now, hense the delay. It also seems like the x86 and x64 versions may need to be separate too, which is unfortunate.

**Comment by ThatLinuxNerd** [comment]
Obviously I got that issue addressed. As I'm very new to scoop I'm unsure to how I would make the game folder similar to $dir.

**Comment by issaclin32** [comment]
The script will cause error, because you are copying files from **both 64-bit and 32-bit** paths, while it should actually be *arch-specific*. You should either use `if ($architecture -eq '64bit') { ... }` or use `extract_dir` like:

```
    "architecture": {
        "64bit": {
            "url": [
                "https://cdn.openttd.org/openttd-releases/12.1/openttd-12.1-windows-win64.zip",
                "https://cdn.openttd.org/opengfx-releases/7.1/opengfx-7.1-all.zip",
                "https://cdn.openttd.org/opensfx-releases/1.0.3/opensfx-1.0.3-all.zip",
                "https://cdn.openttd.org/openmsx-releases/0.4.2/openmsx-0.4.2-all.zip"
            ],
            "hash": [
                "fe909797a3aa9ef1f7080b28685f7a668b8b47fed4db427109e65c3de9468304",
                "928fcf34efd0719a3560cbab6821d71ce686b6315e8825360fba87a7a94d7846",
                "e0a218b7dd9438e701503b0f84c25a97c1c11b7c2f025323fb19d6db16ef3759",
                "5a4277a2e62d87f2952ea5020dc20fb2f6ffafdccf9913fbf35ad45ee30ec762"
            ],
            "extract_dir": "openttd-12.1-windows-win64"
        },
        "32bit": {
            "url": [
                "https://cdn.openttd.org/openttd-releases/12.1/openttd-12.1-windows-win32.zip",
                "https://cdn.openttd.org/opengfx-releases/7.1/opengfx-7.1-all.zip",
                "https://cdn.openttd.org/opensfx-releases/1.0.3/opensfx-1.0.3-all.zip",
                "https://cdn.openttd.org/openmsx-releases/0.4.2/openmsx-0.4.2-all.zip"
            ],
            "hash": [
                "d071b3d8ca71d4df217f3924b371d7e1743d15111a8e4f056470d584eb84d5a1",
                "928fcf34efd0719a3560cbab6821d71ce686b6315e8825360fba87a7a94d7846",
                "e0a218b7dd9438e701503b0f84c25a97c1c11b7c2f025323fb19d6db16ef3759",
                "5a4277a2e62d87f2952ea5020dc20fb2f6ffafdccf9913fbf35ad45ee30ec762"
            ],
            "extract_dir": "openttd-12.1-windows-win32"
        }
    },
```

**Comment by Calinou** [comment]
Superseded by https://github.com/Calinou/scoop-games/pull/606. Thanks for the contribution nonetheless!

**Pull request closed without merging**
