### PR TITLE
Update mgba-dev.json

### LINKED ISSUE #342: mgba-dev@7137-20211015: current directory is moved
When I install mgba-dev, the current directory is moved to the install directory.

PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)

pwd

Path
----
C:\Users\user\scoop\apps\mgba-dev\7137-20211015

### PR DESCRIPTION
**Pull request by satorope**
Changed the name of bin to avoid conflict with the stable version.
Fix: current directory is moved

Closes #342

### CODE REVIEW

**Comment by beyondmeat** [comment]
@Calinou not sure why this was done but probably can close

**Comment by Calinou** [comment]
> @Calinou not sure why this was done but probably can close

Isn't the original issue still present right now?

**Comment by beyondmeat** [comment]
@Calinou if you want to alias dev/nightly bin and shortcuts then it should be merged.

**Comment by beyondmeat** [comment]
@Calinou this can be closed everything has been addressed in this pr and it's not defunct.

**Comment by Calinou** [comment]
Closing per @beyondmeat's comment. Thanks for the contribution nonetheless :slightly_smiling_face:

**Pull request closed without merging**
